# Application URL
base.url=http://192.168.100.170/ens/

# Browser (chrome / firefox / edge)
browser=Chrome

# Implicit wait in seconds
implicit.wait=10

# Explicit wait in seconds
explicit.wait=15

# Environment
env=QA

# Application credentials
app.username=admin
app.password=Telesuite@8765

# Screenshot path
screenshot.path=screenshots/

# Report path
report.path=test-output/ExtentReport/CallAuditReport.html

report.logopath=https://sam-182002.github.io/tsl_logo.png
